import { StyleSheet } from 'react-native';

export const setupStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8FAFC' },
  container: { flex: 1, paddingHorizontal: 20 },
  topHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 15, marginBottom: 5 },
  brand: { color: '#64748b', fontSize: 10, fontWeight: '800', letterSpacing: 2 },
  stepIndicator: { backgroundColor: '#f1f5f9', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  stepText: { color: '#475569', fontSize: 10, fontWeight: '900' },
  titleSection: { marginTop: 15 },
  title: { fontSize: 26, fontWeight: '900', color: '#0f172a', letterSpacing: -0.5 },
  subtitle: { marginTop: 4, fontSize: 14, color: '#64748b', fontWeight: '500' },
  progressContainer: { marginTop: 25 },
  progressTrack: { height: 6, backgroundColor: '#e2e8f0', borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#3b82f6', borderRadius: 3 },
  progressLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 },
  progressLabel: { fontSize: 10, fontWeight: '800', color: '#94a3b8', letterSpacing: 1 },
  activeLabel: { color: '#3b82f6' },
  searchWrapper: { marginTop: 20 },
  search: {
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    fontWeight: '600',
    color: '#1e293b',
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  listWrapper: { flex: 1, marginTop: 10 },
  listContent: { paddingTop: 10, paddingBottom: 30 },
  stationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#64748b',
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 3,
  },
  lineIndicator: { width: 5, height: 35, borderRadius: 3, marginRight: 15 },
  stationBody: { flex: 1 },
  stationName: { fontSize: 16, fontWeight: '800', color: '#1e293b' },
  stationMeta: { fontSize: 11, color: '#94a3b8', marginTop: 2, fontWeight: '600' },
  actionCircle: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#f1f5f9', alignItems: 'center', justifyContent: 'center' },
  actionArrow: { fontSize: 16, color: '#475569', fontWeight: 'bold' },
  
  trainCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 8,
  },
  trainHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 15 },
  trainTag: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  trainTagText: { color: '#FFF', fontSize: 11, fontWeight: '900', fontFamily: 'monospace' },
  timeContainer: { alignItems: 'flex-end' },
  timeLabel: { fontSize: 9, fontWeight: '800', color: '#94a3b8', marginBottom: 2 },
  timeValue: { fontSize: 22, fontWeight: '900', color: '#0f172a', fontFamily: 'monospace' },
  destBox: { marginBottom: 20 },
  destTitle: { fontSize: 20, fontWeight: '900', color: '#1e293b', letterSpacing: -0.5 },
  routeSubtitle: { fontSize: 12, color: '#64748b', marginTop: 4, fontWeight: '500' },
  trainFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 15, borderTopWidth: 1, borderTopColor: '#f1f5f9' },
  footerInfo: { flexDirection: 'row', alignItems: 'center' },
  dot: { width: 8, height: 8, borderRadius: 4, marginRight: 8 },
  footerText: { fontSize: 11, color: '#475569', fontWeight: '700' },
  selectBtn: { backgroundColor: '#0f172a', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 12 },
  selectBtnText: { color: '#FFF', fontSize: 10, fontWeight: '900', letterSpacing: 1 },

  filterContainer: { marginTop: 16, marginBottom: 8 },
  filterChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 25, borderWidth: 1, borderColor: '#e2e8f0', marginRight: 10, backgroundColor: '#FFF' },
  filterText: { fontSize: 11, fontWeight: '800', color: '#64748b' },

  routePreview: {
    marginTop: 20,
    backgroundColor: '#1e293b',
    padding: 20,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
    marginBottom: 10,
  },
  radarHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  routeTitle: { fontSize: 11, fontWeight: '900', color: '#94a3b8', letterSpacing: 1 },
  radarDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#3b82f6' },
  instructionStep: { flexDirection: 'row', marginBottom: 20 },
  stepBadge: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#334155', alignItems: 'center', justifyContent: 'center', marginRight: 15 },
  stepBadgeText: { color: '#FFF', fontSize: 12, fontWeight: '900' },
  stepContent: { flex: 1 },
  stepInstr: { fontSize: 15, color: '#f8fafc', fontWeight: '600', lineHeight: 22 },
  boldText: { fontWeight: '900', color: '#3b82f6' },
  stepSubInstr: { fontSize: 12, color: '#94a3b8', marginTop: 4, fontWeight: '500' },
  transitHintBox: { marginTop: 10, paddingTop: 15, borderTopWidth: 1, borderTopColor: '#334155' },
  transitHint: { fontSize: 11, color: '#3b82f6', fontWeight: '900', letterSpacing: 0.5 },
  transitSubHint: { fontSize: 10, color: '#64748b', marginTop: 4, fontWeight: '500' },
  backBtn: { paddingVertical: 20, alignItems: 'center' },
  backText: { fontSize: 12, color: '#94a3b8', fontWeight: '800', letterSpacing: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  loadingText: { marginTop: 20, color: '#475569', fontWeight: '800', fontSize: 13, letterSpacing: 1 },
});
